sudo: required

services:
  - docker

install:
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

script:
  - docker build -t $DOCKER_IMAGE_NAME .

env:
  global:
    - DOCKER_IMAGE_NAME=i05nagai/doxygen
